controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\FirstForm;
use app\models\Post;
use app\models\Comment;
use app\models\SignupForm;
use PicoFeed\Syndication\Rss20FeedBuilder;
use PicoFeed\Syndication\Rss20ItemBuilder;
use yii\helpers\Url;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'logout', 'signup'],
                'rules' => [
                        [
                        'allow' => TRUE,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                        [
                        'allow' => TRUE,
                        'actions' => ['logout'],
                        'roles' => ['@']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {

        $query = Post::find()->orderBy('created_at DESC');
        $pagination = new \yii\data\Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $title = Post::find()->select('subject')->orderBy('id DESC')->all();

        $model = $query->offset($pagination->offset)
                ->limit($pagination->limit)
                ->all();

        $tag= \app\models\Tag::find()->all();
        return $this->render('index', ['posts' => $model,'tags'=>$tag, 'titles' => $title, 'pagination' => $pagination]);
    }

    public function actionPost() {
        $comments = Comment::find()->all();
        $comment = new Comment();
        $titles = Post::find()->select('subject')->all();
        $title = \yii\helpers\Html::encode(Yii::$app->request->get('title'));
        $post = Post::find()->where(['subject' => $title])->one();

        $comment->post_id = $post->id;
        if ($comment->load(Yii::$app->request->post()) && $comment->validate()) {
            $comment->created_at = time();
            $comment->save();
            Yii::$app->session->setFlash('PostCreated');
            return $this->redirect(['post', 'title' => $post->subject]);
        }
        return $this->render('post', ['model' => $post, 'comment' => $comment, 'comments' => $comments, 'titles' => $titles]);
    }
    
    public function actionTag(){
        $tag= \yii\helpers\Html::encode(Yii::$app->request->get('title'));
        $tag= \app\models\Tag::find()->where(['name'=>$tag])->one();
        $posts=$tag->getPosts()->all();
        $title = Post::find()->select('subject')->orderBy('id DESC')->all();
        $tags= \app\models\Tag::find()->all();
        return $this->render('tag',['model'=>$posts,'tags'=>$tags, 'titles' => $title]);
    }

    public function actionShow() {
        $model = new FirstForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            return $this->render('showpost', ['model' => $model]);
        } else {
            return $this->render('develop', ['model' => $model]);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout() {
        return $this->render('about');
    }

    public function actionRss() {
        //echo Url::to(['site/rss'],TRUE);exit;
        $feedBuilder = Rss20FeedBuilder::create()
                ->withTitle('وبسایت خبری من')
                ->withAuthor('admin')
                ->withFeedUrl(Url::to(['site/rss']))
                ->withSiteUrl(Url::to(['site/index'],TRUE))
                ->withDate(new \DateTime());
        $posts = Post::find()->orderBy('id DESC')->limit(5)->all();
        foreach ($posts as $post) {
            $text= mb_substr($post->text, 0,150).'..........';
            $feedBuilder
                    ->withItem(Rss20ItemBuilder::create($feedBuilder)
                            ->withTitle($post->subject)
                            ->withUrl(Url::to(['site/post','title'=>$post->subject],TRUE))
                            ->withAuthor('admin')
                            ->withPublishedDate(new \DateTime('@'.$post->created_at))
                            ->withSummary($text)
                            ->withContent($text)
            );
        }
        echo $feedBuilder->build();
    }

}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>    


    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/develop.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<div class="col-md-6">
    
    <?php $form= ActiveForm::begin(); ?>

    <?= $form->field($model, 'username'); ?>

    <?= $form->field($model, 'password')->passwordInput(); ?>

    <?= $form->field($model, 'email'); ?>


    <?= Html::submitButton('Send ' , ['class' => 'btn btn-primary']); ?>
    <?php $form= ActiveForm::end(); ?>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\data\Pagination;
use yii\widgets\LinkPager;
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = 'صفحه اصلی';
?>



<div class="row">
    <div class="col-md-2">


        <div class="panel panel-default mrg-btm-10">
            <div class="panel-heading">آخرین مطالب</div>
            <div class="panel-body">
                <?php
                foreach ($titles as $title) :
                    ?>
                    <a href="<?= Url::to(['site/post', 'title' => $title->subject]) ?>"><?= $title->subject ?></a>

                    <hr class="no-margin padd-top-btm-5">
                <?php endforeach; ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">موضوعات</h3>
            </div>
            <div class="panel-body">
                <ul>
                <?php foreach ($tags as $tag): ?>
                    <li><a href="<?= Url::to(['site/tag','title'=>$tag->name])?>"><?=$tag->name?></a></li>
                <?php     endforeach; ?>
                </ul>
            </div>
        </div>

    </div>
    <div class="col-md-10">


        <?php
        foreach ($posts as $post):
            ?>

            <div class="panel panel-default mrg-btm-10">
                <div class="panel-heading text-center"><?= $post->subject ?></div>
                <div class="panel-body">
                    <?= $post->text ?>
                </div>
            </div>
            <?php
        endforeach;
        ?>


    </div>
</div>



<div class="text-center linkPager">
    <p>
        <?=
        LinkPager::widget(['pagination' => $pagination]);
        ?>
    </p>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/post.php
<?php
if (empty($model))
    exit;

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
$this->title = 'صفحه اصلی';
?>



<div class="row">
    <div class="col-md-2">
        <div class="panel panel-default mrg-btm-10">
            <div class="panel-heading">آخرین مطالب</div>
            <div class="panel-body">
                <?php
                foreach ($titles as $title) :
                    ?>
                    <a href="<?= Url::to(['site/post', 'title' => $title->subject]) ?>"><?= $title->subject ?></a>

                    <hr class="no-margin padd-top-btm-5">
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="col-md-10">


        
        <div class="panel panel-default mrg-btm-10">
            <div class="panel-heading text-center"><?= $model->subject ?></div>
            <div class="panel-body">
                <?= $model->text ?>
            </div>
        </div>



        <div class="col-md-12 thumbnail padd-14">
            <h3 class="page-header text-success">نظرات شما</h3>
            <?php foreach ($comments as $c) : ?>
                <div class="alert bg-info border-pnlcomment"> نوشته شده توسط :<?= $c->from ?> در تاریخ :<?= Yii::$app->formatter->asDate($c->created_at, 'php:d-m-Y') ?>
                    <hr class="hrComment">
                    <p class="text-justify"><?= $c->text ?></p>
                </div>
            <?php endforeach; ?>

        </div>
        <div class="clearfix"></div>

        <?php if (!Yii::$app->session->hasFlash('PostCreated')) : ?>
            <div class="col-md-12 thumbnail padd-14">
                <br>
                <?php $form = ActiveForm::begin(); ?>

                <?= $form->field($comment, 'from')->textInput(['maxlength' => true]) ?>

                <?= $form->field($comment, 'email')->textInput(['maxlength' => true]) ?>

                <?= $form->field($comment, 'text')->textarea(['rows' => 6]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        <?php else : ?>
            <div class="alert alert-success">پیغام شما با موفقیت ثبت شد</div>
        <?php endif; ?>

    </div>
</div>

views/site/showpost.php
<?php

use yii\helpers\Html;
?>

<?=Html::encode($model->username);?><br>
<?=Html::encode($model->password);?><br>
<?=Html::encode($model->email);?>

views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/tag.php
<?php

use yii\helpers\Url;
?>
<div class="row">

    <div class="col-md-2">
        <div class="panel panel-default mrg-btm-10">
            <div class="panel-heading">آخرین مطالب</div>
            <div class="panel-body">
                <?php
                foreach ($titles as $title) :
                    ?>
                    <a href="<?= Url::to(['site/post', 'title' => $title->subject]) ?>"><?= $title->subject ?></a>

                    <hr class="no-margin padd-top-btm-5">
                <?php endforeach; ?>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">موضوعات</h3>
            </div>
            <div class="panel-body">
                <ul>
                <?php foreach ($tags as $tag): ?>
                    <li><a href="<?= Url::to(['site/tag','title'=>$tag->name])?>"><?=$tag->name?></a></li>
                <?php     endforeach; ?>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-10">
        <?php foreach ($model as $post) : ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $post->subject ?></h3>
                </div>
                <div class="panel-body">
                    <?= $post->text ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

</div>